# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
# Student.delete_all
# Classroom.delete_all

Classroom.create([
   {address: "25 Sterns Lane, Copiague, NY", monthly_fee: 6000, sqft: 7000, class_size: 15, provide_meals: true}, 
   {address: "10 Broadway St, Manhattan, NY", monthly_fee: 6000, sqft: 7000, class_size: 15, provide_meals: true },
   {address: "244 Upper East Side, Manhattan, NY", monthly_fee: 6000, sqft: 7000, class_size: 15, provide_meals: true}, 
   {address: "12 Abunderale Ave, Valley Stream, NY", monthly_fee: 6000, sqft: 7000, class_size: 15, provide_meals: true}, 
   {address: "98 Chambers St, NY", monthly_fee: 6000, sqft: 7000, class_size: 15, provide_meals: true},
   {address: "135-12 Rockaway Blvd, Queens, NY",monthly_fee: 6000, sqft: 7000, class_size: 15, provide_meals: true},
   {address: "14th Street, Union Ave, NY", monthly_fee: 6000, sqft: 7000, class_size: 15, provide_meals: true},
   {address: "600 Old Country Road, Hicksville, NY", monthly_fee: 6000, sqft: 7000, class_size: 15, provide_meals: true} 
])


Student.create([
   {first_name: "Waseem", last_name: "Nafisi", age: 1, class_id: 1},
   {first_name: "Muhammad", last_name: "Ibin kaleb", age: 1, class_id: 1},
   {first_name: "Tala", last_name: "Aljazari", age: 1, class_id: 1},
   {first_name: "Tagreed", last_name: "Tina", age: 2, class_id: 1},
   {first_name: "Basil", last_name: "nafisi", age: 2, class_id: 1},
   {first_name: "Osama", last_name: "nafisi", age: 2, class_id: 1},
   {first_name: "Sami", last_name: "Ceo", age: 2, class_id: 1},
   {first_name: "Pendra", last_name: "Pratt", age: 2, class_id: 1},
   {first_name: "Wesey", last_name: "Dwarika", age: 1, class_id: 2},
   {first_name: "Maya", last_name: "Sonia", age: 1, class_id: 2},
   {first_name: "Timothy", last_name: "sikes", age: 1, class_id: 2},
   {first_name: "Priyanka", last_name: "Chopra", age: 2, class_id: 2},
   {first_name: "Barney", last_name: "Nelson", age: 2, class_id: 2},
   {first_name: "Odin", last_name: "Thurt", age: 2, class_id: 2},
   {first_name: "Silver", last_name: "Erin", age: 2, class_id: 2},
   {first_name: "Penolope", last_name: "Prince", age: 2, class_id: 2},
   {first_name: "Shaniya", last_name:"Bad", age: 1, class_id: 3},
   {first_name: "Varsha", last_name:"Vanessa", age: 1, class_id: 3},
   {first_name: "Keron", last_name:"Baal", age: 2, class_id: 3},
   {first_name: "Kevon", last_name:"Vidal", age: 2, class_id: 3},
   {first_name: "Vin", last_name:"Kalpoo", age: 1, class_id: 3},
   {first_name: "Vik", last_name:"Haricharran", age: 2, class_id: 3},
   {first_name: "Randy", last_name:"Mikey", age: 2, class_id: 3},
   {first_name: "Anthony", last_name:"Lean", age: 2, class_id: 3},
   {first_name: "Justin", last_name:"Rajkumar", age: 1, class_id: 3},
   {first_name: "Junior", last_name:"Johnny", age: 2, class_id: 3},
   {first_name: "Jonathon", last_name:"Singh", age: 1, class_id: 3},
   {first_name: "Lena", last_name:"Singh", age: 2, class_id: 3},
   {first_name: "Naveeta", last_name:"Rajaram", age: 2, class_id: 4},
   {first_name: "Manny", last_name:"Choudhary", age: 1, class_id: 4},
   {first_name: "Alisha", last_name:"Bal", age: 2, class_id: 4},
   {first_name: "Julia", last_name:"Balkaran", age: 1, class_id: 4},
   {first_name: "Jasmine", last_name:"Tommy", age: 2, class_id: 4},
   {first_name: "Jessica", last_name:"Nick", age: 1, class_id: 4},
   {first_name: "Shua", last_name:"Wolf", age: 2, class_id: 5},
   {first_name: "Elizabeth", last_name:"Fun", age: 2, class_id: 5},
   {first_name: "Elizabeth", last_name:"Costey", age: 2, class_id: 5},
   {first_name: "Jonathon", last_name:"Lora", age: 1, class_id: 5},
   {first_name: "Kenny", last_name:"Zee", age: 2, class_id: 5},
   {first_name: "Chris", last_name:"Lin", age: 1, class_id: 5},
   {first_name: "Christopher", last_name:"Caraballo", age: 2, class_id: 5},
   {first_name: "Genisis", last_name:"Moran", age: 1, class_id: 6},
   {first_name: "Ginny", last_name:"Gutang", age: 2, class_id: 6},
   {first_name: "Tylaine", last_name:"Geoffery", age: 1, class_id: 6},
   {first_name: "Geoff", last_name:"Harnet", age: 2, class_id: 6},
   {first_name: "Will", last_name:"William", age: 1, class_id: 6},
   {first_name: "Jodie", last_name:"Molino", age: 2, class_id: 6},
   {first_name: "Shivanie", last_name:"Ramnarine", age: 2, class_id: 6},
   {first_name: "Shenese", last_name:"Roopnarine", age: 1, class_id: 6},
   {first_name: "Tyler", last_name:"Jubraj", age: 2, class_id: 6},
   {first_name: "Alex", last_name:"Gibson", age: 2, class_id: 7},
   {first_name: "Riky", last_name:"Shakka", age: 2, class_id: 7},
   {first_name: "Alex", last_name:"Lutchman", age: 1, class_id: 7},
   {first_name: "Drake", last_name:"Aubrey", age: 2, class_id: 7},
   {first_name: "Beyonce", last_name:"Knowles", age: 2, class_id: 7},
   {first_name: "Rihanna", last_name:"Fenty", age: 1, class_id: 7},
   {first_name: "Cardi", last_name:"Bee", age: 2, class_id: 7},
   {first_name: "Chris", last_name:"Brown", age: 1, class_id: 7},
   {first_name: "Wayne", last_name:"Carter", age: 2, class_id: 8},
   {first_name: "Kim", last_name:"West", age: 2, class_id: 8},
   {first_name: "Khloe", last_name:"Thompson", age: 2, class_id: 8},
   {first_name: "Kylie", last_name:"Jenner", age: 1, class_id: 8},
   {first_name: "Kendall", last_name:"Jnner", age: 2, class_id: 8},
   {first_name: "Kourtney", last_name:"Discic", age: 1, class_id: 8},
   {first_name: "Danny", last_name:"kim", age: 2, class_id: 8},
   {first_name: "Dianne", last_name:"Stukes", age: 1, class_id: 8},
   {first_name: "Shwin", last_name:"zuin", age: 2, class_id: 8},
   {first_name: "Aeisha", last_name:"Burrows", age: 1, class_id: 8},
   {first_name: "Solomon", last_name:"Sokoya", age: 2, class_id: 8},
   {first_name: "Genaya", last_name:"James", age: 2, class_id: 8},
   {first_name: "Nick", last_name:"Cannon", age: 1, class_id: 4},
   {first_name: "Machael", last_name:"Montano", age: 2, class_id: 4},
   {first_name: "Patrice", last_name:"Roberts", age: 1, class_id: 4},
   {first_name: "Pritivi", last_name:"Bheem", age: 2, class_id: 4},
   {first_name: "Vandana", last_name:"Persad", age: 1, class_id: 4},
   {first_name: "Kassen", last_name:"Mitchel", age: 2, class_id: 3},
   {first_name: "Phillip", last_name:"Paul", age: 1, class_id: 3},
   {first_name: "Rohan", last_name:"Taran", age: 2, class_id: 3},
   {first_name: "Andrew", last_name:"John", age: 1, class_id: 3}
])